/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProvenanceID = IDL.Record({
  'id' : IDL.Text,
  'productName' : IDL.Text,
  'physicalHash' : IDL.Text,
  'creationDate' : IDL.Int,
  'attributes' : IDL.Vec(
    IDL.Record({ 'trait_type' : IDL.Text, 'value' : IDL.Text })
  ),
  'batchNumber' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ORIGYNMetadata = IDL.Record({
  'id' : IDL.Nat,
  'provenance' : ProvenanceID,
  'verified' : IDL.Bool,
  'manufacturer_details' : IDL.Text,
  'provenance_id' : IDL.Text,
  'collection' : IDL.Text,
  'discountCode' : IDL.Text,
  'redeemed' : IDL.Bool,
  'name' : IDL.Text,
  'certification' : IDL.Text,
  'mystery' : IDL.Bool,
  'asset_class' : IDL.Text,
  'issue_date' : IDL.Text,
  'media_assets' : IDL.Vec(ExternalBlob),
  'product' : IDL.Text,
});
export const Time = IDL.Int;
export const AddressBookEntry = IDL.Record({
  'principal' : IDL.Principal,
  'nickname' : IDL.Text,
  'createdAt' : Time,
  'updatedAt' : Time,
});
export const TransactionType = IDL.Variant({
  'burn' : IDL.Null,
  'mint' : IDL.Null,
  'transfer' : IDL.Null,
});
export const TransactionRecord = IDL.Record({
  'to' : IDL.Opt(IDL.Principal),
  'transactionType' : TransactionType,
  'metadata' : ORIGYNMetadata,
  'from' : IDL.Opt(IDL.Principal),
  'user' : IDL.Principal,
  'nftId' : IDL.Nat,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'profileImage' : IDL.Opt(ExternalBlob),
  'forgeTheme' : IDL.Text,
});
export const RedemptionRecord = IDL.Record({
  'metadata' : ORIGYNMetadata,
  'user' : IDL.Principal,
  'nftId' : IDL.Nat,
  'timestamp' : Time,
});
export const NFTData = IDL.Record({
  'id' : IDL.Nat,
  'provenance' : ProvenanceID,
  'verified' : IDL.Bool,
  'manufacturer_details' : IDL.Text,
  'provenance_id' : IDL.Text,
  'collection' : IDL.Text,
  'owner' : IDL.Principal,
  'creationTimestamp' : Time,
  'discountCode' : IDL.Text,
  'redeemed' : IDL.Bool,
  'name' : IDL.Text,
  'origyn_metadata' : ORIGYNMetadata,
  'certification' : IDL.Text,
  'mystery' : IDL.Bool,
  'asset_class' : IDL.Text,
  'issue_date' : IDL.Text,
  'media_assets' : IDL.Vec(ExternalBlob),
  'product' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAddressBookEntry' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'batchMintNFTs' : IDL.Func(
      [IDL.Vec(ORIGYNMetadata), IDL.Vec(IDL.Vec(ExternalBlob))],
      [IDL.Vec(IDL.Nat)],
      [],
    ),
  'burnNFT' : IDL.Func([IDL.Nat], [], []),
  'deleteAddressBookEntry' : IDL.Func([IDL.Principal], [], []),
  'getAddressBook' : IDL.Func([], [IDL.Vec(AddressBookEntry)], ['query']),
  'getAllNFTs' : IDL.Func([], [IDL.Vec(ORIGYNMetadata)], ['query']),
  'getAllTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(TransactionRecord)],
      ['query'],
    ),
  'getArchivedNFT' : IDL.Func([IDL.Nat], [ORIGYNMetadata], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
      ['query'],
    ),
  'getOwnedNFTs' : IDL.Func([], [IDL.Vec(ORIGYNMetadata)], ['query']),
  'getRedemptionHistory' : IDL.Func([], [IDL.Vec(RedemptionRecord)], ['query']),
  'getTransactionHistory' : IDL.Func(
      [],
      [IDL.Vec(TransactionRecord)],
      ['query'],
    ),
  'getUserNFTs' : IDL.Func([], [IDL.Vec(NFTData)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isLeaderboardVisible' : IDL.Func([], [IDL.Bool], ['query']),
  'mintNFT' : IDL.Func([ORIGYNMetadata, IDL.Vec(ExternalBlob)], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleLeaderboardVisibility' : IDL.Func([], [], []),
  'transferNFT' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'updateAddressBookEntry' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProvenanceID = IDL.Record({
    'id' : IDL.Text,
    'productName' : IDL.Text,
    'physicalHash' : IDL.Text,
    'creationDate' : IDL.Int,
    'attributes' : IDL.Vec(
      IDL.Record({ 'trait_type' : IDL.Text, 'value' : IDL.Text })
    ),
    'batchNumber' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ORIGYNMetadata = IDL.Record({
    'id' : IDL.Nat,
    'provenance' : ProvenanceID,
    'verified' : IDL.Bool,
    'manufacturer_details' : IDL.Text,
    'provenance_id' : IDL.Text,
    'collection' : IDL.Text,
    'discountCode' : IDL.Text,
    'redeemed' : IDL.Bool,
    'name' : IDL.Text,
    'certification' : IDL.Text,
    'mystery' : IDL.Bool,
    'asset_class' : IDL.Text,
    'issue_date' : IDL.Text,
    'media_assets' : IDL.Vec(ExternalBlob),
    'product' : IDL.Text,
  });
  const Time = IDL.Int;
  const AddressBookEntry = IDL.Record({
    'principal' : IDL.Principal,
    'nickname' : IDL.Text,
    'createdAt' : Time,
    'updatedAt' : Time,
  });
  const TransactionType = IDL.Variant({
    'burn' : IDL.Null,
    'mint' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const TransactionRecord = IDL.Record({
    'to' : IDL.Opt(IDL.Principal),
    'transactionType' : TransactionType,
    'metadata' : ORIGYNMetadata,
    'from' : IDL.Opt(IDL.Principal),
    'user' : IDL.Principal,
    'nftId' : IDL.Nat,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'profileImage' : IDL.Opt(ExternalBlob),
    'forgeTheme' : IDL.Text,
  });
  const RedemptionRecord = IDL.Record({
    'metadata' : ORIGYNMetadata,
    'user' : IDL.Principal,
    'nftId' : IDL.Nat,
    'timestamp' : Time,
  });
  const NFTData = IDL.Record({
    'id' : IDL.Nat,
    'provenance' : ProvenanceID,
    'verified' : IDL.Bool,
    'manufacturer_details' : IDL.Text,
    'provenance_id' : IDL.Text,
    'collection' : IDL.Text,
    'owner' : IDL.Principal,
    'creationTimestamp' : Time,
    'discountCode' : IDL.Text,
    'redeemed' : IDL.Bool,
    'name' : IDL.Text,
    'origyn_metadata' : ORIGYNMetadata,
    'certification' : IDL.Text,
    'mystery' : IDL.Bool,
    'asset_class' : IDL.Text,
    'issue_date' : IDL.Text,
    'media_assets' : IDL.Vec(ExternalBlob),
    'product' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAddressBookEntry' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'batchMintNFTs' : IDL.Func(
        [IDL.Vec(ORIGYNMetadata), IDL.Vec(IDL.Vec(ExternalBlob))],
        [IDL.Vec(IDL.Nat)],
        [],
      ),
    'burnNFT' : IDL.Func([IDL.Nat], [], []),
    'deleteAddressBookEntry' : IDL.Func([IDL.Principal], [], []),
    'getAddressBook' : IDL.Func([], [IDL.Vec(AddressBookEntry)], ['query']),
    'getAllNFTs' : IDL.Func([], [IDL.Vec(ORIGYNMetadata)], ['query']),
    'getAllTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(TransactionRecord)],
        ['query'],
      ),
    'getArchivedNFT' : IDL.Func([IDL.Nat], [ORIGYNMetadata], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Nat))],
        ['query'],
      ),
    'getOwnedNFTs' : IDL.Func([], [IDL.Vec(ORIGYNMetadata)], ['query']),
    'getRedemptionHistory' : IDL.Func(
        [],
        [IDL.Vec(RedemptionRecord)],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func(
        [],
        [IDL.Vec(TransactionRecord)],
        ['query'],
      ),
    'getUserNFTs' : IDL.Func([], [IDL.Vec(NFTData)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isLeaderboardVisible' : IDL.Func([], [IDL.Bool], ['query']),
    'mintNFT' : IDL.Func(
        [ORIGYNMetadata, IDL.Vec(ExternalBlob)],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleLeaderboardVisibility' : IDL.Func([], [], []),
    'transferNFT' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'updateAddressBookEntry' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };