/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddressBookEntry {
  'principal' : Principal,
  'nickname' : string,
  'createdAt' : Time,
  'updatedAt' : Time,
}
export type ExternalBlob = Uint8Array;
export interface ORIGYNMetadata {
  'id' : bigint,
  'provenance' : ProvenanceID,
  'verified' : boolean,
  'manufacturer_details' : string,
  'provenance_id' : string,
  'collection' : string,
  'discountCode' : [] | [string],
  'redeemed' : boolean,
  'name' : string,
  'certification' : string,
  'mystery' : boolean,
  'asset_class' : string,
  'issue_date' : string,
  'media_assets' : Array<ExternalBlob>,
  'product' : string,
}
export interface ProvenanceID {
  'id' : string,
  'productName' : string,
  'physicalHash' : string,
  'creationDate' : bigint,
  'attributes' : Array<{ 'trait_type' : string, 'value' : string }>,
  'batchNumber' : string,
}
export interface PublicNFTData {
  'id' : bigint,
  'provenance' : ProvenanceID,
  'verified' : boolean,
  'manufacturer_details' : string,
  'provenance_id' : string,
  'collection' : string,
  'owner' : Principal,
  'creationTimestamp' : Time,
  'redeemed' : boolean,
  'name' : string,
  'origyn_metadata' : PublicORIGYNMetadata,
  'certification' : string,
  'mystery' : boolean,
  'asset_class' : string,
  'issue_date' : string,
  'media_assets' : Array<ExternalBlob>,
  'product' : string,
}
export interface PublicORIGYNMetadata {
  'id' : bigint,
  'provenance' : ProvenanceID,
  'verified' : boolean,
  'manufacturer_details' : string,
  'provenance_id' : string,
  'collection' : string,
  'redeemed' : boolean,
  'name' : string,
  'certification' : string,
  'mystery' : boolean,
  'asset_class' : string,
  'issue_date' : string,
  'media_assets' : Array<ExternalBlob>,
  'product' : string,
}
export interface PublicTransactionRecord {
  'to' : [] | [Principal],
  'transactionType' : TransactionType,
  'metadata' : PublicORIGYNMetadata,
  'from' : [] | [Principal],
  'user' : Principal,
  'nftId' : bigint,
  'timestamp' : Time,
}
export interface RedemptionRecord {
  'discountCode' : string,
  'metadata' : PublicORIGYNMetadata,
  'user' : Principal,
  'nftId' : bigint,
  'timestamp' : Time,
}
export type Time = bigint;
export interface TransactionRecord {
  'to' : [] | [Principal],
  'transactionType' : TransactionType,
  'metadata' : ORIGYNMetadata,
  'from' : [] | [Principal],
  'user' : Principal,
  'nftId' : bigint,
  'timestamp' : Time,
}
export type TransactionType = { 'burn' : null } |
  { 'mint' : null } |
  { 'transfer' : null };
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'profileImage' : [] | [ExternalBlob],
  'forgeTheme' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAddressBookEntry' : ActorMethod<[Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'batchMintNFTs' : ActorMethod<
    [Array<ORIGYNMetadata>, Array<Array<ExternalBlob>>],
    Array<bigint>
  >,
  'burnNFT' : ActorMethod<[bigint], string>,
  'deleteAddressBookEntry' : ActorMethod<[Principal], undefined>,
  'getAddressBook' : ActorMethod<[], Array<AddressBookEntry>>,
  'getAllNFTs' : ActorMethod<[], Array<ORIGYNMetadata>>,
  'getAllTransactionHistory' : ActorMethod<[], Array<TransactionRecord>>,
  'getArchivedNFT' : ActorMethod<[bigint], ORIGYNMetadata>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<[], Array<[Principal, bigint]>>,
  'getOwnedNFTs' : ActorMethod<[], Array<PublicORIGYNMetadata>>,
  'getRedemptionHistory' : ActorMethod<[], Array<RedemptionRecord>>,
  'getTransactionHistory' : ActorMethod<[], Array<PublicTransactionRecord>>,
  'getUserNFTs' : ActorMethod<[], Array<PublicNFTData>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isLeaderboardVisible' : ActorMethod<[], boolean>,
  'mintNFT' : ActorMethod<[ORIGYNMetadata, Array<ExternalBlob>], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleLeaderboardVisibility' : ActorMethod<[], undefined>,
  'transferNFT' : ActorMethod<[bigint, Principal], undefined>,
  'updateAddressBookEntry' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];