/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ProvenanceID {
    id: string;
    productName: string;
    physicalHash: string;
    creationDate: bigint;
    attributes: Array<{
        trait_type: string;
        value: string;
    }>;
    batchNumber: string;
}
export interface ORIGYNMetadata {
    id: bigint;
    provenance: ProvenanceID;
    verified: boolean;
    manufacturer_details: string;
    provenance_id: string;
    collection: string;
    discountCode: string;
    redeemed: boolean;
    name: string;
    certification: string;
    mystery: boolean;
    asset_class: string;
    issue_date: string;
    media_assets: Array<ExternalBlob>;
    product: string;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface AddressBookEntry {
    principal: Principal;
    nickname: string;
    createdAt: Time;
    updatedAt: Time;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface RedemptionRecord {
    metadata: ORIGYNMetadata;
    user: Principal;
    nftId: bigint;
    timestamp: Time;
}
export interface UserProfile {
    bio: string;
    displayName: string;
    profileImage?: ExternalBlob;
    forgeTheme: string;
}
export interface TransactionRecord {
    to?: Principal;
    transactionType: TransactionType;
    metadata: ORIGYNMetadata;
    from?: Principal;
    user: Principal;
    nftId: bigint;
    timestamp: Time;
}
export enum TransactionType {
    burn = "burn",
    mint = "mint",
    transfer = "transfer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addAddressBookEntry(principal: Principal, nickname: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    batchMintNFTs(metadataList: Array<ORIGYNMetadata>, mediaAssetsList: Array<Array<ExternalBlob>>): Promise<Array<bigint>>;
    burnNFT(nftId: bigint): Promise<void>;
    deleteAddressBookEntry(principal: Principal): Promise<void>;
    getAddressBook(): Promise<Array<AddressBookEntry>>;
    getAllNFTs(): Promise<Array<ORIGYNMetadata>>;
    getAllTransactionHistory(): Promise<Array<TransactionRecord>>;
    getArchivedNFT(nftId: bigint): Promise<ORIGYNMetadata>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLeaderboard(): Promise<Array<[Principal, bigint]>>;
    getOwnedNFTs(): Promise<Array<ORIGYNMetadata>>;
    getRedemptionHistory(): Promise<Array<RedemptionRecord>>;
    getTransactionHistory(): Promise<Array<TransactionRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isLeaderboardVisible(): Promise<boolean>;
    mintNFT(metadata: ORIGYNMetadata, mediaAssets: Array<ExternalBlob>): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleLeaderboardVisibility(): Promise<void>;
    transferNFT(nftId: bigint, to: Principal): Promise<void>;
    updateAddressBookEntry(principal: Principal, newNickname: string): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, ORIGYNMetadata as _ORIGYNMetadata, ProvenanceID as _ProvenanceID, RedemptionRecord as _RedemptionRecord, Time as _Time, TransactionRecord as _TransactionRecord, TransactionType as _TransactionType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addAddressBookEntry(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAddressBookEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAddressBookEntry(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async batchMintNFTs(arg0: Array<ORIGYNMetadata>, arg1: Array<Array<ExternalBlob>>): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.batchMintNFTs(await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0), await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.batchMintNFTs(await to_candid_vec_n10(this._uploadFile, this._downloadFile, arg0), await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async burnNFT(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.burnNFT(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.burnNFT(arg0);
            return result;
        }
    }
    async deleteAddressBookEntry(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAddressBookEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAddressBookEntry(arg0);
            return result;
        }
    }
    async getAddressBook(): Promise<Array<AddressBookEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAddressBook();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAddressBook();
            return result;
        }
    }
    async getAllNFTs(): Promise<Array<ORIGYNMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNFTs();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNFTs();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactionHistory(): Promise<Array<TransactionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactionHistory();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactionHistory();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArchivedNFT(arg0: bigint): Promise<ORIGYNMetadata> {
        if (this.processError) {
            try {
                const result = await this.actor.getArchivedNFT(arg0);
                return from_candid_ORIGYNMetadata_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArchivedNFT(arg0);
            return from_candid_ORIGYNMetadata_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(): Promise<Array<[Principal, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getOwnedNFTs(): Promise<Array<ORIGYNMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnedNFTs();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnedNFTs();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRedemptionHistory(): Promise<Array<RedemptionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRedemptionHistory();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRedemptionHistory();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionHistory(): Promise<Array<TransactionRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isLeaderboardVisible(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isLeaderboardVisible();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isLeaderboardVisible();
            return result;
        }
    }
    async mintNFT(arg0: ORIGYNMetadata, arg1: Array<ExternalBlob>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.mintNFT(await to_candid_ORIGYNMetadata_n11(this._uploadFile, this._downloadFile, arg0), await to_candid_vec_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.mintNFT(await to_candid_ORIGYNMetadata_n11(this._uploadFile, this._downloadFile, arg0), await to_candid_vec_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleLeaderboardVisibility(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLeaderboardVisibility();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLeaderboardVisibility();
            return result;
        }
    }
    async transferNFT(arg0: bigint, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transferNFT(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferNFT(arg0, arg1);
            return result;
        }
    }
    async updateAddressBookEntry(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAddressBookEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAddressBookEntry(arg0, arg1);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_ORIGYNMetadata_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ORIGYNMetadata): Promise<ORIGYNMetadata> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
async function from_candid_RedemptionRecord_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RedemptionRecord): Promise<RedemptionRecord> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_TransactionRecord_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionRecord): Promise<TransactionRecord> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n28(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    provenance: _ProvenanceID;
    verified: boolean;
    manufacturer_details: string;
    provenance_id: string;
    collection: string;
    discountCode: string;
    redeemed: boolean;
    name: string;
    certification: string;
    mystery: boolean;
    asset_class: string;
    issue_date: string;
    media_assets: Array<_ExternalBlob>;
    product: string;
}): Promise<{
    id: bigint;
    provenance: ProvenanceID;
    verified: boolean;
    manufacturer_details: string;
    provenance_id: string;
    collection: string;
    discountCode: string;
    redeemed: boolean;
    name: string;
    certification: string;
    mystery: boolean;
    asset_class: string;
    issue_date: string;
    media_assets: Array<ExternalBlob>;
    product: string;
}> {
    return {
        id: value.id,
        provenance: value.provenance,
        verified: value.verified,
        manufacturer_details: value.manufacturer_details,
        provenance_id: value.provenance_id,
        collection: value.collection,
        discountCode: value.discountCode,
        redeemed: value.redeemed,
        name: value.name,
        certification: value.certification,
        mystery: value.mystery,
        asset_class: value.asset_class,
        issue_date: value.issue_date,
        media_assets: await from_candid_vec_n19(_uploadFile, _downloadFile, value.media_assets),
        product: value.product
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: [] | [Principal];
    transactionType: _TransactionType;
    metadata: _ORIGYNMetadata;
    from: [] | [Principal];
    user: Principal;
    nftId: bigint;
    timestamp: _Time;
}): Promise<{
    to?: Principal;
    transactionType: TransactionType;
    metadata: ORIGYNMetadata;
    from?: Principal;
    user: Principal;
    nftId: bigint;
    timestamp: Time;
}> {
    return {
        to: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.to)),
        transactionType: from_candid_TransactionType_n25(_uploadFile, _downloadFile, value.transactionType),
        metadata: await from_candid_ORIGYNMetadata_n17(_uploadFile, _downloadFile, value.metadata),
        from: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.from)),
        user: value.user,
        nftId: value.nftId,
        timestamp: value.timestamp
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    profileImage: [] | [_ExternalBlob];
    forgeTheme: string;
}): Promise<{
    bio: string;
    displayName: string;
    profileImage?: ExternalBlob;
    forgeTheme: string;
}> {
    return {
        bio: value.bio,
        displayName: value.displayName,
        profileImage: record_opt_to_undefined(await from_candid_opt_n30(_uploadFile, _downloadFile, value.profileImage)),
        forgeTheme: value.forgeTheme
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metadata: _ORIGYNMetadata;
    user: Principal;
    nftId: bigint;
    timestamp: _Time;
}): Promise<{
    metadata: ORIGYNMetadata;
    user: Principal;
    nftId: bigint;
    timestamp: Time;
}> {
    return {
        metadata: await from_candid_ORIGYNMetadata_n17(_uploadFile, _downloadFile, value.metadata),
        user: value.user,
        nftId: value.nftId,
        timestamp: value.timestamp
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    burn: null;
} | {
    mint: null;
} | {
    transfer: null;
}): TransactionType {
    return "burn" in value ? TransactionType.burn : "mint" in value ? TransactionType.mint : "transfer" in value ? TransactionType.transfer : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ORIGYNMetadata>): Promise<Array<ORIGYNMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ORIGYNMetadata_n17(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransactionRecord>): Promise<Array<TransactionRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TransactionRecord_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RedemptionRecord>): Promise<Array<RedemptionRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_RedemptionRecord_n34(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_ORIGYNMetadata_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ORIGYNMetadata): Promise<_ORIGYNMetadata> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    provenance: ProvenanceID;
    verified: boolean;
    manufacturer_details: string;
    provenance_id: string;
    collection: string;
    discountCode: string;
    redeemed: boolean;
    name: string;
    certification: string;
    mystery: boolean;
    asset_class: string;
    issue_date: string;
    media_assets: Array<ExternalBlob>;
    product: string;
}): Promise<{
    id: bigint;
    provenance: _ProvenanceID;
    verified: boolean;
    manufacturer_details: string;
    provenance_id: string;
    collection: string;
    discountCode: string;
    redeemed: boolean;
    name: string;
    certification: string;
    mystery: boolean;
    asset_class: string;
    issue_date: string;
    media_assets: Array<_ExternalBlob>;
    product: string;
}> {
    return {
        id: value.id,
        provenance: value.provenance,
        verified: value.verified,
        manufacturer_details: value.manufacturer_details,
        provenance_id: value.provenance_id,
        collection: value.collection,
        discountCode: value.discountCode,
        redeemed: value.redeemed,
        name: value.name,
        certification: value.certification,
        mystery: value.mystery,
        asset_class: value.asset_class,
        issue_date: value.issue_date,
        media_assets: await to_candid_vec_n13(_uploadFile, _downloadFile, value.media_assets),
        product: value.product
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    displayName: string;
    profileImage?: ExternalBlob;
    forgeTheme: string;
}): Promise<{
    bio: string;
    displayName: string;
    profileImage: [] | [_ExternalBlob];
    forgeTheme: string;
}> {
    return {
        bio: value.bio,
        displayName: value.displayName,
        profileImage: value.profileImage ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.profileImage)) : candid_none(),
        forgeTheme: value.forgeTheme
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ORIGYNMetadata>): Promise<Array<_ORIGYNMetadata>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ORIGYNMetadata_n11(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<ExternalBlob>>): Promise<Array<Array<_ExternalBlob>>> {
    return await Promise.all(value.map(async (x)=>await to_candid_vec_n13(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
